### ISSUE TITLE
Release up-to-date version on PyPi?

### ISSUE THREAD

**Issue by bdewilde** [wwrechard/PyDLM#15]
Hey, thanks for the nice lib! I was wondering if you'd be able to increment and release an up-to-date version to PyPi. If not, do you have any sense of when a new version will be released?

**Comment by wwrechard** [comment]
Hi bdewilde,

Thanks for reminding me! A newer version has been released on PyPI. I usually release a newer version when there is 'significant' change in the library. But I think it is better to have more regular release cycles and I will be likely to set up one so that I can push myself to finish all the feature requests in time : )

Thanks again!
