### ISSUE TITLE
Cannot use setLoggingLevel

### ISSUE THREAD

**Issue by alencn1024** [wwrechard/PyDLM#70]
when I try to use setLoggingLevel to reduce unnecessary output info, there is an error

**Comment by alencn1024** [comment]
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/tmp/ipykernel_617/3387016881.py in <module>
      8 # Build a simple dlm
      9 simple_dlm = dlm(time_series) + linear_trend + seasonal52
---> 10 simple_dlm.setLoggingLevel('WARNING')
     11 simple_dlm.fit()

AttributeError: 'dlm' object has no attribute 'setLoggingLevel'

**Comment by alencn1024** [comment]
![image](https://github.com/user-attachments/assets/dabc5bcb-d2b4-45ce-9d40-cf0bd8473d94)
I run the example showing in the readme file

**Comment by wwrechard** [comment]
Hi @alencn1024 I think you were using the `pip` installed package instead of the Github version, that's why the `setLoggingLevel` was not available. I've just released the Github version on PyPI (0.1.1.13). If you update your package to the latest version, you shall be able to run the command with no problem.

**Comment by alencn1024** [comment]
@wwrechard Cool! it works now, thx very much!
